### ISSUE TITLE
Add unit of injuries$weight to documentation

### ISSUE THREAD

**Issue by jemus42** [hadley/neiss#2]
I'm assuming `injuries$weight` is kilograms, but I'm not sure because the US is known for its use of non-standardized units. Also, `mean(injuries$weight)` of about 36.58 seems too low to be the national weight average in kilograms, but I could just be underestimating the number of children in the dataset.

**Comment by juliasilge** [comment]
The quantity `weight` is not the weight of the person injured, but a weight assigned to the injury so that that injury can be used to get a national estimate. It explains this a bit more in the [NEISS coding manual](https://www.cpsc.gov//Global/Neiss_prod/2016NonTraumaNEISSCodingManual.pdf).

![screen shot 2016-02-20 at 10 43 22 am](https://cloud.githubusercontent.com/assets/12505835/13198168/1d4dd190-d7bf-11e5-93f0-964fb3f58bf4.png)

To get a national estimate, sum the weights of the injuries you are interested in.

**Comment by jemus42** [comment]
Welp, now I'm embarrassed for not reading the manual.  
Thanks for clearing that up, I hope it's okay that I close this issue :)
